<a href="https://colab.research.google.com/github/Rathamsettygovardhan/Life_expectancy-Data-preprocessing-EDA-Wrangling/blob/master/prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Linear Regression

In [2]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, mean_absolute_error
from sklearn import preprocessing

In [3]:
## Fetching the Life expectancy dataset that is ready for modelling

In [5]:
df1=pd.read_csv('/content/drive/MyDrive/ColabNotebooks/finalmerged.csv')
df=df1.iloc[:,1:]
df

,AdultMortality,Alcohol,BMI,Country,Diphtheria,GDP,HIV/AIDS,HepatitisB,Incomecompositionofresources,Lifeexpectancy,...,Totalexpenditure,Year,infantdeaths,percentageexpenditure,Cereal_import_dependence,Arable_land_equipped_for_irrigation,Population_with_basic_drinking_water,Undernourished_pop,Crime,alco_value
0,263,0.01,19.1,Afghanistan,65.0,584.259210,0.1,65.0,0.479,65.0,...,8.16,2015.0,62.0,71.279624,34.2,41.5,61.3,7.800000,-2.570000,0.00
1,271,0.01,18.6,Afghanistan,62.0,612.700000,0.1,62.0,0.476,59.9,...,8.18,2014.0,64.0,73.523582,27.0,41.4,58.7,7.400000,-2.410000,0.00
2,268,0.01,18.1,Afghanistan,64.0,631.700000,0.1,64.0,0.470,59.9,...,8.13,2013.0,66.0,73.219243,23.2,41.3,56.0,6.900000,-2.520000,0.01
3,272,0.01,17.6,Afghanistan,67.0,669.959000,0.1,67.0,0.463,59.5,...,8.52,2012.0,69.0,78.184215,21.0,41.2,53.4,6.700000,-2.420000,0.01
4,275,0.01,17.2,Afghanistan,68.0,63.500000,0.1,68.0,0.454,59.2,...,7.87,2011.0,71.0,7.097100,26.2,41.2,50.8,6.600000,-2.500000,0.01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2901,723,4.36,27.1,Zimbabwe,65.0,454.400000,33.6,68.0,0.407,44.3,...,7.13,2004.0,27.0,0.000000,28.7,4.1,70.7,5.589222,-1.210000,2.64
2902,715,4.06,26.7,Zimbabwe,68.0,453.351155,36.7,7.0,0.418,44.5,...,6.52,2003.0,26.0,0.000000,23.8,4.2,71.2,5.589222,-1.090000,2.72
2903,73,4.43,26.3,Zimbabwe,71.0,57.348340,39.8,73.0,0.427,44.8,...,6.53,2002.0,25.0,0.000000,31.6,4.3,71.7,5.589222,-1.520000,2.50
2904,686,1.72,25.9,Zimbabwe,75.0,548.600000,42.1,76.0,0.427,45.3,...,6.16,2001.0,25.0,0.000000,22.5,4.3,72.0,5.589222,-0.085951,2.48
2905,665,1.68,25.5,Zimbabwe,78.0,547.358878,43.5,79.0,0.434,46.0,...,7.10,2000.0,24.0,0.000000,11.7,4.4,71.9,5.589222,-1.320000,2.48

In [6]:
df.isnull().sum()

AdultMortality                          0
Alcohol                                 0
BMI                                     0
Country                                 0
Diphtheria                              8
GDP                                     0
HIV/AIDS                                0
HepatitisB                              0
Incomecompositionofresources            0
Lifeexpectancy                          0
Measles                                 0
Polio                                   0
Population                              0
Schooling                               0
Status                                  0
Totalexpenditure                        0
Year                                    0
infantdeaths                            0
percentageexpenditure                   0
Cereal_import_dependence                0
Arable_land_equipped_for_irrigation     0
Population_with_basic_drinking_water    0
Undernourished_pop                      0
Crime                                   0
alco_value                              0
dtype: int64

In [8]:
df.fillna(0, inplace=True)    # 1 Attribute with Nulls, Vaccination for 8 records can be replaced with 0.

In [9]:
x=df.drop(['Lifeexpectancy'], axis=1)
y=df['Lifeexpectancy']

In [10]:
# Object type attributes are wrangled for modeling using get_dummies method.

In [11]:
x = pd.get_dummies(data=x, drop_first=True)     
x

,AdultMortality,Alcohol,BMI,Diphtheria,GDP,HIV/AIDS,HepatitisB,Incomecompositionofresources,Measles,Polio,...,Country_United States of America,Country_Uruguay,Country_Uzbekistan,Country_Vanuatu,Country_Venezuela (Bolivarian Republic of),Country_Viet Nam,Country_Yemen,Country_Zambia,Country_Zimbabwe,Status_Developing
0,263,0.01,19.1,65.0,584.259210,0.1,65.0,0.479,1154.0,6.0,...,0,0,0,0,0,0,0,0,0,1
1,271,0.01,18.6,62.0,612.700000,0.1,62.0,0.476,492.0,58.0,...,0,0,0,0,0,0,0,0,0,1
2,268,0.01,18.1,64.0,631.700000,0.1,64.0,0.470,430.0,62.0,...,0,0,0,0,0,0,0,0,0,1
3,272,0.01,17.6,67.0,669.959000,0.1,67.0,0.463,2787.0,67.0,...,0,0,0,0,0,0,0,0,0,1
4,275,0.01,17.2,68.0,63.500000,0.1,68.0,0.454,3013.0,68.0,...,0,0,0,0,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2901,723,4.36,27.1,65.0,454.400000,33.6,68.0,0.407,31.0,67.0,...,0,0,0,0,0,0,0,0,1,1
2902,715,4.06,26.7,68.0,453.351155,36.7,7.0,0.418,998.0,7.0,...,0,0,0,0,0,0,0,0,1,1
2903,73,4.43,26.3,71.0,57.348340,39.8,73.0,0.427,304.0,73.0,...,0,0,0,0,0,0,0,0,1,1
2904,686,1.72,25.9,75.0,548.600000,42.1,76.0,0.427,529.0,76.0,...,0,0,0,0,0,0,0,0,1,1
2905,665,1.68,25.5,78.0,547.358878,43.5,79.0,0.434,1483.0,78.0,...,0,0,0,0,0,0,0,0,1,1

In [12]:
#Train-Test Split

In [13]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2)

In [14]:
#Applying

In [15]:
from sklearn.linear_model import LinearRegression
reg_model = LinearRegression()
reg_model.fit(x, y)
y_predicted = reg_model.predict(x_test)
y_predicted

array([53.91616284, 60.66772645, 74.45280272, 53.87810003, 64.836815  ,
       83.50620173, 54.96953918, 81.44979038, 68.93335013, 70.05295544,
       82.58779686, 72.37180991, 56.13987221, 72.9492986 , 73.80151828,
       49.37708165, 70.13687956, 56.18809691, 73.51935521, 69.48131593,
       54.19135743, 64.17531398, 81.32815841, 73.63945694, 82.61789813,
       63.0096651 , 58.47812197, 74.57209621, 64.57019735, 58.5308351 ,
       80.2505734 , 72.25129789, 77.02509234, 74.01117789, 48.25060598,
       68.79426753, 61.39190392, 43.88872383, 58.09325331, 72.87342119,
       76.4657229 , 67.7649593 , 76.8098683 , 70.80828332, 56.04808643,
       82.4757857 , 75.77788094, 74.6716311 , 63.77911224, 66.20246629,
       74.53668988, 72.2554203 , 76.4000954 , 71.86321895, 74.41537944,
       42.26899267, 52.24401625, 78.30909581, 54.83036561, 75.9699894 ,
       74.93935678, 69.35134703, 68.62486179, 72.48189986, 69.96375937,
       81.81213989, 69.83029856, 53.75233722, 74.14208652, 77.00418663,
       84.3024318 , 57.45107006, 54.41879724, 54.48074751, 54.8794925 ,
       73.94471561, 75.89525353, 55.93455349, 73.90480007, 71.5473441 ,
       56.59394072, 56.05664626, 65.1387896 , 74.47363091, 58.95729066,
       74.30996364, 65.35834035, 72.40238996, 70.5426729 , 53.40625022,
       76.93355318, 73.15845079, 73.0702954 , 74.09599889, 78.62782079,
       72.84984882, 72.78721371, 60.35479796, 75.59481752, 73.64864357,
       76.21290834, 51.44172471, 74.39046052, 73.86879343, 62.9805966 ,
       61.70677014, 72.37940608, 55.62684686, 79.3705846 , 82.43288213,
       49.87315341, 71.79319314, 74.43641438, 74.77548861, 68.93357186,
       74.15869528, 81.22320419, 60.71325433, 73.04994069, 63.25209085,
       55.57613896, 73.19464118, 74.635225  , 74.42531364, 55.01941386,
       54.67196886, 66.75782111, 59.04523936, 52.59718797, 67.16399592,
       49.58758238, 71.76023576, 54.52676112, 73.81583588, 69.41212103,
       75.58529922, 77.51651818, 73.23758971, 76.69357495, 72.99569643,
       65.1248019 , 73.31687913, 62.68632526, 55.91572122, 46.8720993 ,
       72.62928404, 49.55367657, 69.73893909, 84.16151056, 74.52045168,
       58.26505564, 64.13775865, 73.74993253, 79.74127345, 56.04661155,
       69.5909106 , 75.93154747, 75.57933312, 74.56713116, 76.70200627,
       74.11812778, 77.61445961, 73.40072855, 64.6294822 , 72.24280861,
       77.15278448, 82.93118422, 75.27929787, 54.51422716, 74.7383034 ,
       67.64108431, 63.77070761, 73.98747462, 70.15483135, 81.72258322,
       56.71757342, 67.05491823, 68.02286907, 78.53634682, 78.32222996,
       71.7213197 , 49.54783699, 73.74582377, 74.39852237, 60.77038466,
       69.30581102, 74.02843151, 73.46311984, 62.45683626, 82.92459079,
       50.20844827, 80.37232207, 59.46056549, 79.80069202, 59.95129071,
       57.67543843, 67.30025697, 73.24364627, 64.7144713 , 74.71274916,
       65.33650671, 82.6003746 , 62.91464995, 69.3155577 , 76.33072152,
       55.76032333, 67.37159639, 75.26282209, 62.75926217, 51.84276466,
       61.01003065, 75.78213696, 73.65208782, 54.72876421, 76.64508587,
       70.61568889, 62.23941155, 78.29272727, 76.24145135, 75.61089788,
       83.77030503, 46.26010389, 68.11196603, 73.35915246, 54.93210764,
       68.51206729, 81.44432838, 63.47064887, 75.19726357, 78.07229544,
       50.05421912, 51.50551786, 75.79660335, 54.60461257, 82.48613603,
       72.61624768, 66.0962635 , 72.59265314, 82.21031204, 74.82219301,
       62.4163706 , 81.82862462, 66.98593429, 72.11823073, 77.36731124,
       75.89075707, 84.48291815, 53.40757828, 74.34607328, 72.1073363 ,
       67.19214103, 62.54564615, 82.24944895, 74.41378859, 54.10705058,
       69.64442358, 67.0010749 , 71.27580931, 71.73166368, 75.36055211,
       75.8401149 , 76.09100886, 68.50551978, 70.79618785, 69.90401875,
       77.9168745 , 67.78592659, 57.0715221 , 59.37011993, 69.92712821,
       73.13738675, 56.59585074, 70.55781769, 66.50190325, 75.21406479,
       72.56182184, 72.46580085, 80.2300372 , 57.98819298, 64.64309101,
       72.49667161, 59.07183735, 80.38230703, 62.01686018, 80.69516109,
       64.73213497, 62.4284748 , 66.18707413, 68.55391831, 74.48841407,
       80.74531111, 68.91794579, 63.00766206, 66.29106965, 66.42594115,
       73.98318174, 53.08936898, 79.70628805, 53.28061765, 75.16750792,
       75.40911297, 44.22577864, 61.06655974, 73.96327791, 67.62726293,
       75.61009945, 76.61676664, 71.25476884, 56.37864005, 68.67075227,
       81.25852567, 77.14761298, 46.91688622, 64.75529401, 66.53115096,
       71.70540709, 65.21717031, 71.5561464 , 78.83075324, 52.75570681,
       57.64403693, 74.61454208, 73.87130763, 68.81150812, 73.36925772,
       80.48888738, 68.23492006, 74.33013814, 80.83246924, 48.5653442 ,
       75.09576961, 67.80108485, 77.07336442, 73.35927544, 61.58949521,
       54.7279419 , 48.39284638, 74.40628265, 61.71104056, 73.28407914,
       58.99964245, 47.230536  , 45.12026063, 71.98002735, 76.40943659,
       72.83096636, 64.05938235, 73.48491015, 65.76331185, 70.88982225,
       77.9802961 , 73.73517474, 69.21999912, 83.09562736, 75.84163804,
       69.68160104, 68.15270683, 75.41242953, 72.64088018, 50.61464643,
       60.53694424, 78.4667324 , 83.75696241, 62.35941281, 67.66572477,
       56.25351866, 68.63496383, 71.67205355, 65.05176325, 63.21715036,
       73.84481068, 81.39720077, 56.92486187, 54.40205302, 52.68919314,
       77.1817572 , 49.96270083, 62.68572087, 74.90482903, 57.33398057,
       59.27719689, 58.74863025, 72.25484634, 63.92189771, 54.93650191,
       74.92682488, 71.65520494, 59.29684797, 58.81015305, 56.5988227 ,
       82.55246057, 63.31702811, 79.07165009, 68.239276  , 82.52744874,
       75.9667584 , 58.9815519 , 71.24855799, 75.67589408, 73.34881853,
       57.66213696, 74.96842211, 81.63084884, 82.93153425, 59.34085047,
       72.1087158 , 58.33670075, 82.46613114, 71.87607865, 59.93112467,
       56.3763525 , 69.6090006 , 79.91767895, 79.68356883, 65.88752958,
       68.82273535, 80.5516158 , 68.63502232, 73.19180685, 75.43721808,
       72.22129528, 81.8794003 , 73.27863266, 53.27755768, 66.45079598,
       74.70608415, 66.79168775, 74.0219118 , 75.3813916 , 81.26937722,
       73.68367574, 75.67819251, 73.01400509, 51.46303187, 60.12411068,
       69.35349328, 74.568448  , 71.94098148, 80.69850939, 71.31944352,
       69.71843664, 71.82148549, 62.11093709, 72.78365903, 49.08865821,
       76.04803654, 72.42397977, 81.41796034, 81.07863992, 67.95644105,
       61.3989466 , 70.86986807, 74.59641572, 52.87382563, 66.248808  ,
       58.31865506, 81.01431476, 68.94071078, 58.98610857, 72.81022545,
       72.5560234 , 74.85384575, 83.54191223, 74.6510745 , 55.43730523,
       67.76665526, 74.61687548, 60.0397858 , 45.89499685, 67.09926533,
       61.05969263, 63.30028028, 70.93269297, 72.95181525, 71.74851897,
       57.62174535, 60.66113298, 75.84092052, 79.05415396, 72.87409313,
       55.54542709, 76.12100453, 58.45941622, 71.67217582, 71.8874276 ,
       54.89154982, 75.92062049, 62.65819082, 72.5775585 , 77.95024748,
       59.0585518 , 74.72828044, 72.67915964, 81.34878032, 67.73588406,
       73.50805106, 65.90257117, 48.30098809, 52.49433821, 59.62205796,
       69.79059045, 82.77017639, 75.47449737, 75.92109432, 82.42692821,
       73.06353743, 78.56563598, 74.83125207, 73.25054451, 77.50540386,
       68.56617423, 71.33643307, 73.73296717, 82.37845048, 45.05099431,
       83.96015193, 60.19684087, 68.07901098, 63.17542626, 67.2556077 ,
       73.44567579, 84.04443658, 52.05866095, 64.7295955 , 83.97526434,
       65.48063393, 71.84679646, 68.35618242, 74.75275145, 75.24896052,
       49.09073079, 47.72952866, 73.37854176, 80.52038287, 73.96317129,
       79.59755647, 62.04163093, 80.97928755, 51.57349154, 75.09312744,
       51.79233336, 54.90840874, 75.45233511, 82.01179739, 61.76990728,
       65.8439818 , 50.49722839, 58.97167378, 81.9718605 , 73.52025617,
       69.17365457, 60.72173181, 73.31176483, 72.99301972, 46.39976066,
       72.12836342, 52.42580441, 69.21999909, 75.34725151, 75.98509059,
       68.84861006, 69.77636551, 74.788745  , 72.41516248, 66.48377382,
       66.60149372, 82.30589275, 71.55323505, 72.63248679, 79.08177294,
       79.92963483, 53.36458059, 60.3974067 , 76.80642151, 61.4424328 ,
       80.76016939, 81.2941371 , 79.46484516, 79.52104718, 74.14606485,
       70.3643841 , 80.4618275 ])

In [17]:
reg_model.score(x_test,y_test)     #Accuracy score   96.8%

0.968854101876411

In [19]:
viz=df1.iloc[x_test.index]
viz1=viz['Lifeexpectancy']
viz1

1105    52.1
1366    61.2
2012    73.7
487     54.2
1387    65.0
        ...
658     79.0
927     78.1
451     72.7
783     71.4
1546    79.7
Name: Lifeexpectancy, Length: 582, dtype: float64

In [20]:
# Predicted Label values of 20% tested data vs Original Label values.

In [21]:
vizdf=pd.DataFrame(data=viz1)
vizdf['y_Predicted']=y_predicted
vizdf

      Lifeexpectancy  y_Predicted
1105            52.1    53.916163
1366            61.2    60.667726
2012            73.7    74.452803
487             54.2    53.878100
1387            65.0    64.836815
...              ...          ...
658             79.0    79.464845
927             78.1    79.521047
451             72.7    74.146065
783             71.4    70.364384
1546            79.7    80.461828

[582 rows x 2 columns]

In [22]:
print('mean_squared_error : ', mean_squared_error(y_test, y_predicted))
print('mean_absolute_error : ', mean_absolute_error(y_test, y_predicted))

mean_squared_error :  2.913911639672191
mean_absolute_error :  1.0846946667747401

In [23]:
#Printing the predicted with original

In [24]:
import matplotlib.pyplot as plt
import plotly.express as px
px.scatter(vizdf,x='Lifeexpectancy', y='y_Predicted')

In [25]:
x_test

,AdultMortality,Alcohol,BMI,Diphtheria,GDP,HIV/AIDS,HepatitisB,Incomecompositionofresources,Measles,Polio,...,Country_United States of America,Country_Uruguay,Country_Uzbekistan,Country_Vanuatu,Country_Venezuela (Bolivarian Republic of),Country_Viet Nam,Country_Yemen,Country_Zambia,Country_Zimbabwe,Status_Developing
1105,3,2.84,17.4,49.0,297.751944,3.1,81.0,0.000,0.0,52.0,...,0,0,0,0,0,0,0,0,0,1
1366,278,1.80,19.5,96.0,987.445397,3.4,96.0,0.530,2395.0,97.0,...,0,0,0,0,0,0,0,0,0,1
2012,14,4.72,52.2,93.0,522.500000,0.2,93.0,0.708,0.0,92.0,...,0,0,0,0,0,0,0,0,0,1
487,382,5.90,24.9,84.0,1233.500000,6.7,84.0,0.466,495.0,82.0,...,0,0,0,0,0,0,0,0,0,1
1387,212,0.76,72.8,86.0,1151.600000,0.1,88.0,0.576,0.0,86.0,...,0,0,0,0,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
658,93,4.37,6.7,99.0,75.519900,0.1,97.0,0.772,0.0,99.0,...,0,0,0,0,0,0,0,0,0,1
927,98,9.25,56.6,98.0,26834.262500,0.1,81.0,0.863,0.0,95.0,...,0,0,0,0,0,0,0,0,0,1
451,121,0.01,29.0,94.0,348.500000,0.3,94.0,0.636,0.0,94.0,...,0,0,0,0,0,0,0,0,0,1
783,189,6.43,45.1,82.0,38.465780,2.4,63.0,0.660,0.0,74.0,...,0,0,0,0,0,0,0,0,0,1
1546,82,11.75,57.9,99.0,1618.492800,0.1,87.0,0.877,0.0,96.0,...,0,0,0,0,0,0,0,0,0,0

In [26]:
ind=x_test.index
ind

Int64Index([1105, 1366, 2012,  487, 1387,  932, 1096, 1920, 2522, 2108,
            ...
            1666, 2785,  963, 2488, 1638,  658,  927,  451,  783, 1546],
           dtype='int64', length=582)

In [27]:
df1.drop('Unnamed: 0', axis=1, inplace=True)

In [29]:
df1.iloc[ind]    # Whole Data of random 20% selected by Algorithm, used to crosscheck the machine's performance.

,AdultMortality,Alcohol,BMI,Country,Diphtheria,GDP,HIV/AIDS,HepatitisB,Incomecompositionofresources,Lifeexpectancy,...,Totalexpenditure,Year,infantdeaths,percentageexpenditure,Cereal_import_dependence,Arable_land_equipped_for_irrigation,Population_with_basic_drinking_water,Undernourished_pop,Crime,alco_value
1105,3,2.84,17.4,Guinea-Bissau,49.0,297.751944,3.1,81.0,0.000,52.1,...,4.94,2000.0,5.0,6.699400,41.7,8.500000,56.0,0.200000,-0.35,4.42
1366,278,1.80,19.5,Kenya,96.0,987.445397,3.4,96.0,0.530,61.2,...,5.23,2011.0,60.0,109.705184,33.0,2.600000,55.4,8.800000,-1.24,1.88
2012,14,4.72,52.2,Peru,93.0,522.500000,0.2,93.0,0.708,73.7,...,5.30,2010.0,10.0,69.439345,45.5,61.900000,87.3,2.200000,-1.00,7.84
487,382,5.90,24.9,Cameroon,84.0,1233.500000,6.7,84.0,0.466,54.2,...,5.18,2008.0,56.0,68.707304,27.4,0.500000,61.2,1.700000,-0.55,7.99
1387,212,0.76,72.8,Kiribati,86.0,1151.600000,0.1,88.0,0.576,65.0,...,1.93,2006.0,0.0,18.194579,0.0,28.592012,65.3,0.100000,1.35,3.74
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
658,93,4.37,6.7,Cuba,99.0,75.519900,0.1,97.0,0.772,79.0,...,11.60,2014.0,1.0,13.669102,73.0,21.100000,95.6,5.589222,0.54,5.83
927,98,9.25,56.6,Finland,98.0,26834.262500,0.1,81.0,0.863,78.1,...,7.81,2002.0,0.0,3099.400000,-12.5,4.400000,99.0,5.589222,1.76,11.60
451,121,0.01,29.0,Cabo Verde,94.0,348.500000,0.3,94.0,0.636,72.7,...,4.61,2012.0,0.0,33.558890,97.0,6.800000,83.9,0.100000,0.81,6.87
783,189,6.43,45.1,Dominican Republic,82.0,38.465780,2.4,63.0,0.660,71.4,...,5.79,2002.0,7.0,4.673592,71.8,33.100000,91.2,2.100000,0.12,7.02
1546,82,11.75,57.9,Luxembourg,99.0,1618.492800,0.1,87.0,0.877,79.7,...,6.80,2007.0,0.0,267.100000,14.3,28.592012,99.0,5.589222,1.48,12.90

##Decision Tree

In [30]:
from sklearn.tree import DecisionTreeRegressor
from sklearn.model_selection import train_test_split 
from sklearn import metrics

clf = DecisionTreeRegressor(random_state=1)

clf = clf.fit(x_train,y_train)

y_pred = clf.predict(x_test)

In [31]:
from sklearn.model_selection import cross_val_score
clf.score(x_test, y_test)

0.9158260816191108